kind: Pod
apiVersion: v1
metadata:
  name: hello-app-pvc-2
spec:
  containers:
    - name: hello-app
      image: gcr.io/google-samples/hello-app:1.0
      volumeMounts:
      - mountPath: "/mnt/gke"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-demo-2